### ISSUE TITLE
Typescript compilation issue: Cannot augment module 'currency'

### ISSUE THREAD

**Issue by arturnt** [scurker/currency.js#88]
Running this with typescript 2.4.2 and getting the following error: `error TS2649: Cannot augment module 'currency' with value exports because it resolves to a non-module entity.`

**Comment by scurker** [comment]
How are you importing `currency.js`? I believe I know what the issue might be, but may need to update the documentation to better clarify typescript usage.

**Comment by arturnt** [comment]
Importing it this way: `import * as money from "currency.js";`

**Comment by scurker** [comment]
Typescript is currently tested with the following imports:

```js
import currency from '../src/currency.js';
import * as namedCurrency from '../src/currency.js';
import interopCurrency = require('../src/currency.js');
```

With the following `tsconfig.json`:

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "allowSyntheticDefaultImports": true
  }
}
```

My understanding is that `allowSyntheticDefaultImports` is required for the first, but 2 & 3 should work interchangeably. Ideally, Typescript should be using `import currency from 'currency.js'` since only a single default export is used. I'm still not 100% why `import * as money from 'currency.js'` is breaking, but `import money = require('currency.js')` should work regardless of what your `tsconfig.json` has.

I might be able to address it, I just haven't been able to reproduce your exact issue yet.

**Comment by arturnt** [comment]
I tried changing the target to `es5` and with the `allowSyntheticDefaultImports` property but still had the same issue. The compiler specifically complains about the definition file and highlights the following lines:

```js
declare module 'currency.js' {
  export default currency;
}
```

For what it is worth the following type definition fixes it (just removing the lines above):

```js
declare module 'currency.js' {
   namespace currency {
    type Any = number | string | currency;
    interface Constructor {
      (value: currency.Any, opts?: currency.Options): currency,
      new (value: currency.Any, opts?: currency.Options): currency
    }
    interface Options {
      symbol?: string,
      separator?: string,
      decimal?: string,
      formatWithSymbol?: boolean,
      errorOnInvalid?: boolean,
      precision?: number
    }
  }

   interface currency {
    add(number: currency.Any): currency;
    subtract(number: currency.Any): currency;
    multiply(number: currency.Any): currency;
    divide(number: currency.Any): currency;
    distribute(count: number): Array<currency>;
    dollars(): number;
    cents(): number;
    format(useSymbol?: boolean): string;
    toString(): string;
    toJSON(): number;
    readonly intValue: number;
    readonly value: number;
  }

  const currency : currency.Constructor;
  export = currency;
} ```

**Comment by scurker** [comment]
Thanks for helping me track this down. I think I have a better understanding of the issue, so I just released [`v1.0.8`](https://github.com/scurker/currency.js/releases/tag/v1.0.8) that should fix the problem.

The core of it is rollup bundles the main as a cjs module with `module.exports = currency`, the previous definition had it exporting as a default which didn't match the actual module.

As such, if you use `import currency from 'currency.js'` in typescript, `"allowSyntheticDefaultImports": true` is required in your `tsconfig.json`. Otherwise, `import = require('currency.js')` or `import * as currency from 'currency.js'` should work interchangeably. I need to document this better, but this latest release should fix the issue for you.

**Comment by arturnt** [comment]
Thanks for working on this. Still seeing the same issue: https://imgur.com/a/bQnVe . Is there a reason you need the 

```
declare module 'currency.js' {
  export default currency;
}
```

The code above does fix all the issues and allows me to import in the different ways.

**Comment by scurker** [comment]
I apologize for the back and forth on this, but I wanted to be sure I had everything tied down. I created a [test case](https://gist.github.com/scurker/d07326b2e6772bd55bc5b9258d1e1ef4) for me to work with, and *finally* believe I was able to *really* solve the issue. Unfortunately, tests were passing locally and in ci which mistakenly led me to believe the problem was initially solved.

Here's the quick rundown:

**Interop Resolution**
`import currency = require('currency.js')`
Works universally.

**Default Imports**
`import currency from 'currency.js'`
Only works with `tsconfig.json`:
```js
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true
  }
}
```

**Import As...**
`import * as currency from 'currency.js'`
Only works with `tsconfig.json`:
```js
{
  "compilerOptions": {
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true
  }
}
```

The module that typescript imports does not export a default, so unfortunately some extra help is needed from typescript. I hope this provides some clarity, but `1.09` should have the correct typescript definition file that allows you to use one of the above following imports based on your `tsconfig.json`.

**Comment by ricardovf** [comment]
@scurker i can't make this work in node 10, need urgent help cause i can't deploy this...

using typescript latest version: 3.3.3 and version of currency.js 1.2.1

```bash
tsc -p tsconfig.build.json
```

tsconfig.build.json
```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "target": "es2017",
    "module": "commonjs",
    "declaration": false,
    "noImplicitAny": false,
    "removeComments": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "sourceMap": false,
    "outDir": "./dist",
    "baseUrl": "./"
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "**/*.spec.ts", "**/*.test.ts"]
}
```

somefile.ts
```ts
import currency = require('currency.js');
```

node dist/main.js
```
/Users/ricardo/Code/payface-backend/services/src/face-transaction/entities/face-transaction-intention.entity.ts:3
import currency = require('currency.js');
       ^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
 1: 0x10003ae75 node::Abort() [/Users/ricardo/.nodenv/versions/10.14.0/bin/node]
 2: 0x1000b9707 node::Chdir(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/ricardo/.nodenv/versions/10.14.0/bin/node]
 3: 0x10023035f v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/Users/ricardo/.nodenv/versions/10.14.0/bin/node]
 4: 0x10022f8a1 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/Users/ricardo/.nodenv/versions/10.14.0/bin/node]
 5: 0x10022ef40 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/Users/ricardo/.nodenv/versions/10.14.0/bin/node]
 6: 0x3adc122dbe3d
 7: 0x3adc122918d5
 8: 0x3adc12347578
```

if i change to **import * as currency from 'currency.js';** i get

```import * as currency from 'currency.js';
                  ^

SyntaxError: Unexpected token *
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
```

**Comment by scurker** [comment]
@ricardovf I've moved discussion for your issue over to #180.
